import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import ListenButton from '../components/ListenButton'

const C = {
  bg:        '#0d2818',
  card:      '#163d22',
  border:    '#1f5230',
  red:       '#c0392b',
  accent:    '#1D9E75',
  text:      '#f0ede8',
  textSub:   '#c8e6d0',
  textMuted: '#7aad8a',
}

const P = ({ children, style }) => (
  <p style={{
    fontSize: '16px', color: C.textSub,
    lineHeight: 1.75, marginBottom: '14px',
    ...style,
  }}>
    {children}
  </p>
)

const Card = ({ title, children, cta }) => (
  <div style={{
    display: 'flex', flexDirection: 'column', flex: '1 1 260px',
    background: C.card, border: `1px solid ${C.border}`,
    borderRadius: '12px', padding: '22px',
  }}>
    <div style={{
      fontFamily: "'Big Shoulders Display', sans-serif",
      fontSize: '22px', fontWeight: '900',
      color: C.red, textTransform: 'uppercase',
      letterSpacing: '0.04em', marginBottom: '10px', lineHeight: 1.1,
    }}>
      {title}
    </div>
    <P style={{ marginBottom: '20px' }}>{children}</P>
    <div style={{ marginTop: 'auto' }}>{cta}</div>
  </div>
)

const nodeCtaStyle = {
  display: 'inline-flex', alignItems: 'center', gap: '8px',
  padding: '11px 22px', background: C.accent, color: '#fff',
  borderRadius: '3px', textDecoration: 'none',
  fontFamily: "'Big Shoulders Display', sans-serif", fontSize: '1rem',
  fontWeight: '700', letterSpacing: '0.07em', textTransform: 'uppercase',
}

export default function AboutPage() {
  useEffect(() => {
    document.title = 'About — Magora'
  }, [])

  return (
    <div style={{ maxWidth: '640px', margin: '0 auto', paddingBottom: '56px' }}>

      {/* Hero */}
      <div style={{ marginBottom: '28px' }}>
        <h1 style={{
          fontFamily: "'Big Shoulders Display', sans-serif",
          fontSize: 'clamp(2.4rem, 9vw, 3.4rem)', fontWeight: '900',
          color: C.text, textTransform: 'uppercase',
          letterSpacing: '-0.01em', lineHeight: 1.02, marginBottom: '0',
        }}>
          A window into the living world around you.
        </h1>
      </div>

      <div style={{ height: '1px', background: C.border, marginBottom: '34px' }} />

      {/* Body */}
      <P>
        Most of us move through ecosystems we can't read. The birds calling at dawn, the insects
        hovering over a flower, the fungi threading through the soil beneath your feet — these
        aren't background noise. They're a conversation, and every participant is connected to
        every other. Magora is built to help you hear it.
      </P>
      <P>
        We listen. Acoustic sensors and your phone's microphone capture the soundscape of a
        place — bird species identified by AI, soundscape health measured continuously,
        detections placed in ecological context. But sound is only one angle. Through iNaturalist
        integration, the plants, insects, pollinators, and fungi you observe in the field join
        the same picture. Your journal entries, your observations, your attention — these are
        data too.
      </P>
      <P>
        What emerges from all of those angles, over time, is something no single sensor could
        produce: a relational portrait of an ecosystem. Who's eating what. What's blooming when
        the warblers arrive. Whether the pollinators and the flowers they depend on are still in
        sync. These ecological relationships — threaded across species, across seasons, across
        years — are the signals that tell us how a place is doing, and how a changing climate is
        reshaping the web of life we depend on. Aggregated across Magora's network, they become
        something ecologists and climate scientists can actually use: distributed, ground-level
        phenological data, generated by people paying close attention to the places they know.
      </P>

      <div style={{ borderLeft: `4px solid ${C.red}`, paddingLeft: '18px', margin: '28px 0 8px' }}>
        <span style={{
          fontFamily: "'Big Shoulders Display', sans-serif",
          fontSize: '24px', fontWeight: '900',
          color: C.text, textTransform: 'uppercase', letterSpacing: '0.03em', lineHeight: 1.15,
        }}>
          You don't need to be a scientist to contribute. You need to be somewhere, and willing to look.
        </span>
      </div>

      {/* CTA cards */}
      <div style={{ display: 'flex', gap: '14px', flexWrap: 'wrap', marginTop: '32px' }}>
        <Card
          title="Listen"
          cta={<ListenButton variant="hero" label="Start listening →" />}
        >
          Record ambient sound from wherever you are. The ecosystem will tell you who's there.
        </Card>
        <Card
          title="Deploy a Node"
          cta={<Link to="/register" style={nodeCtaStyle}>Build a node →</Link>}
        >
          A 24-hour listening post that builds the long-term acoustic record of a place.
        </Card>
      </div>

    </div>
  )
}
