import { useState } from 'react'

const HARDWARE_OPTIONS = [
  { id: 'rpi-zero-2w', name: 'Raspberry Pi Zero 2W', sub: 'Recommended · ~$15' },
  { id: 'rpi-4', name: 'Raspberry Pi 4', sub: 'More power · ~$55' },
  { id: 'rpi-3b', name: 'Raspberry Pi 3B+', sub: 'Good balance · ~$35' },
  { id: 'other', name: 'Other / custom', sub: 'Linux SBC' },
]

const HABITAT_OPTIONS = [
  'montane-scrub', 'forest', 'grassland', 'wetland',
  'desert', 'urban-garden', 'farmland', 'coastal', 'other'
]

const C = {
  bg: '#0d2818',
  card: '#163d22',
  border: '#1f5230',
  accent: '#1D9E75',
  accentLight: '#5DCAA5',
  text: '#f0ede8',
  textSub: '#c8e6d0',
  textMuted: '#7aad8a',
}

export default function RegisterNode() {
  const [step, setStep] = useState(1)
  const [hardware, setHardware] = useState('rpi-zero-2w')
  const [form, setForm] = useState({
    nodeName: '', wifi_ssid: '', wifi_password: '',
    lat: '', lon: '', elevation: '', habitat: 'montane-scrub',
  })
  const [nodeId, setNodeId] = useState(null)
  const [nodeEmail, setNodeEmail] = useState(null)
  const [nodePassword, setNodePassword] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  function update(field, value) {
    setForm(f => ({ ...f, [field]: value }))
  }

  async function registerNode() {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/provision-node`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-provision-secret': import.meta.env.VITE_PROVISION_SECRET,
          },
          body: JSON.stringify({
            name: form.nodeName,
            hardware_type: hardware,
            lat: parseFloat(form.lat),
            lon: parseFloat(form.lon),
            elevation_m: parseFloat(form.elevation) || null,
            habitat_type: form.habitat,
          }),
        }
      )
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Provisioning failed')
      setNodeId(data.node_id)
      setNodeEmail(data.email)
      setNodePassword(data.password)
      setStep(4)
    } catch (e) {
      setError(e.message)
    }
    setLoading(false)
  }

  function generateScript() {
    return `#!/bin/bash
# Magora Network — Node Setup Script
# Node: ${form.nodeName}
# Generated by the Magora Portal

set -e
echo "Setting up Magora node: ${form.nodeName}"

cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
    ssid="${form.wifi_ssid}"
    psk="${form.wifi_password}"
}
EOF

cat > /home/magora/location.json << EOF
{
  "lat": ${form.lat},
  "lon": ${form.lon},
  "name": "${form.nodeName}"
}
EOF

cat > /home/magora/secrets.env << EOF
SUPABASE_URL=${import.meta.env.VITE_SUPABASE_URL}
SUPABASE_ANON_KEY=${import.meta.env.VITE_SUPABASE_ANON_KEY}
NODE_EMAIL=${nodeEmail}
NODE_PASSWORD=${nodePassword}
NODE_ID=${nodeId}
EOF

chmod 600 /home/magora/secrets.env

# Enable I2S microphone
sudo sh -c 'echo "\\ndtparam=i2s=on\\ndtoverlay=adau7002-simple" >> /boot/firmware/config.txt'

# Create magora user and directories
sudo useradd -r -s /bin/false magora 2>/dev/null || true
sudo mkdir -p /home/magora
sudo usermod -aG audio magora
sudo chown -R magora:magora /home/magora

# Download firmware
sudo wget -q -O /home/magora/detect.py https://raw.githubusercontent.com/magora-project/magora-acoustic-biodiversity/main/firmware/detect.py
sudo wget -q -O /etc/systemd/system/birdnet.service https://raw.githubusercontent.com/magora-project/magora-acoustic-biodiversity/main/firmware/birdnet.service
sudo systemctl daemon-reload

# Install Python environment
sudo python3 -m venv /home/magora/birdnet-env
sudo /home/magora/birdnet-env/bin/pip install -q birdnetlib astral numpy requests librosa ai-edge-litert
sudo sh -c 'mkdir -p /home/magora/birdnet-env/lib/python3.13/site-packages/tflite_runtime && echo "" > /home/magora/birdnet-env/lib/python3.13/site-packages/tflite_runtime/__init__.py && echo "from ai_edge_litert.interpreter import Interpreter, load_delegate" > /home/magora/birdnet-env/lib/python3.13/site-packages/tflite_runtime/interpreter.py'
sudo chown -R magora:magora /home/magora/birdnet-env
sudo chown magora:magora /home/magora/detect.py

sudo systemctl enable birdnet.service
sudo systemctl start birdnet.service

echo "Setup complete. Node ${form.nodeName} is now active."
`
  }

  function downloadScript() {
    const blob = new Blob([generateScript()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'magora-setup.sh'
    a.click()
  }

  const card = {
    background: C.card, border: `1px solid ${C.border}`,
    borderRadius: '20px', padding: '24px',
  }
  const label = {
    display: 'block', fontSize: '12px', fontWeight: '700',
    color: C.textMuted, textTransform: 'uppercase',
    letterSpacing: '0.06em', marginBottom: '6px',
  }
  const field = { marginBottom: '14px' }
  const btn = {
    width: '100%', background: C.accent, color: '#fff',
    border: 'none', padding: '13px', borderRadius: '12px',
    fontSize: '15px', fontWeight: '700', cursor: 'pointer', marginTop: '4px',
  }

  const steps = ['Account', 'Hardware', 'Location', 'Download']

  return (
    <div style={{ maxWidth: '480px', margin: '0 auto' }}>

      {/* Step indicator */}
      <div style={{ display: 'flex', gap: '0', marginBottom: '24px' }}>
        {steps.map((s, i) => {
          const done = step > i + 1
          const active = step === i + 1
          return (
            <div key={s} style={{ flex: 1, textAlign: 'center' }}>
              <div style={{
                width: '30px', height: '30px', borderRadius: '50%', margin: '0 auto 4px',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: '13px', fontWeight: '700',
                background: done ? C.accent : active ? C.card : C.bg,
                border: `1.5px solid ${done ? C.accent : active ? C.accentLight : C.border}`,
                color: done ? '#fff' : active ? C.accentLight : '#4a7a58',
              }}>
                {done ? '✓' : i + 1}
              </div>
              <div style={{
                fontSize: '11px', fontWeight: '700',
                textTransform: 'uppercase', letterSpacing: '0.06em',
                color: active ? C.accentLight : '#4a7a58',
              }}>{s}</div>
            </div>
          )
        })}
      </div>

      {step === 1 && (
        <div style={card}>
          <div style={{ fontSize: '18px', fontWeight: '700', color: C.text, marginBottom: '4px' }}>Create your account</div>
          <div style={{ fontSize: '13px', color: C.textMuted, marginBottom: '20px' }}>Sign in to register your node</div>
          <div style={field}><label style={label}>Email</label><input type="email" placeholder="you@example.com" /></div>
          <div style={field}><label style={label}>Password</label><input type="password" placeholder="••••••••" /></div>
          <button style={btn} onClick={() => setStep(2)}>Continue</button>
        </div>
      )}

      {step === 2 && (
        <div style={card}>
          <div style={{ fontSize: '18px', fontWeight: '700', color: C.text, marginBottom: '4px' }}>Choose your hardware</div>
          <div style={{ fontSize: '13px', color: C.textMuted, marginBottom: '20px' }}>Select your compute board</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '16px' }}>
            {HARDWARE_OPTIONS.map(hw => (
              <div key={hw.id} onClick={() => setHardware(hw.id)} style={{
                border: `1.5px solid ${hardware === hw.id ? C.accent : C.border}`,
                background: hardware === hw.id ? '#1a4a28' : C.bg,
                borderRadius: '12px', padding: '12px', cursor: 'pointer', textAlign: 'center',
                transition: 'all .15s',
              }}>
                <div style={{ fontSize: '22px', marginBottom: '6px' }}>🖥️</div>
                <div style={{ fontSize: '13px', fontWeight: '700', color: C.text }}>{hw.name}</div>
                <div style={{ fontSize: '11px', color: C.textMuted, marginTop: '2px' }}>{hw.sub}</div>
              </div>
            ))}
          </div>
          <div style={field}>
            <label style={label}>Node name</label>
            <input placeholder="e.g. birdnode2" value={form.nodeName} onChange={e => update('nodeName', e.target.value)} />
          </div>
          <button style={btn} onClick={() => setStep(3)}>Continue to location</button>
        </div>
      )}

      {step === 3 && (
        <div style={card}>
          <div style={{ fontSize: '18px', fontWeight: '700', color: C.text, marginBottom: '4px' }}>Location & network</div>
          <div style={{ fontSize: '13px', color: C.textMuted, marginBottom: '20px' }}>Where is your node and how will it connect?</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
            <div style={field}><label style={label}>Latitude</label><input placeholder="38.83" value={form.lat} onChange={e => update('lat', e.target.value)} /></div>
            <div style={field}><label style={label}>Longitude</label><input placeholder="-104.82" value={form.lon} onChange={e => update('lon', e.target.value)} /></div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
            <div style={field}><label style={label}>Elevation (m)</label><input placeholder="2400" value={form.elevation} onChange={e => update('elevation', e.target.value)} /></div>
            <div style={field}><label style={label}>Habitat type</label>
              <select value={form.habitat} onChange={e => update('habitat', e.target.value)}>
                {HABITAT_OPTIONS.map(h => <option key={h} value={h}>{h}</option>)}
              </select>
            </div>
          </div>
          <div style={field}><label style={label}>WiFi network name (SSID)</label><input placeholder="MyHomeNetwork" value={form.wifi_ssid} onChange={e => update('wifi_ssid', e.target.value)} /></div>
          <div style={field}><label style={label}>WiFi password</label><input type="password" placeholder="••••••••" value={form.wifi_password} onChange={e => update('wifi_password', e.target.value)} /></div>
          {error && <div style={{ color: '#f87171', fontSize: '13px', marginBottom: '10px' }}>{error}</div>}
          <button style={btn} onClick={registerNode} disabled={loading}>
            {loading ? 'Registering node...' : 'Register node & generate setup file'}
          </button>
        </div>
      )}

      {step === 4 && (
        <div style={card}>
          <div style={{ fontSize: '32px', marginBottom: '10px', textAlign: 'center' }}>🎉</div>
          <div style={{ fontSize: '20px', fontWeight: '700', color: C.text, marginBottom: '4px', textAlign: 'center' }}>
            {form.nodeName} registered!
          </div>
          <div style={{ fontSize: '13px', color: C.textMuted, marginBottom: '20px', textAlign: 'center' }}>
            Node ID: {nodeId}
          </div>
          <div style={{ background: C.bg, border: `1px solid ${C.border}`, borderRadius: '12px', padding: '16px', marginBottom: '16px' }}>
            <div style={{ fontSize: '12px', fontWeight: '700', color: C.textMuted, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '10px' }}>Next steps</div>
            {[
              'Download the setup script below',
              'Flash Raspberry Pi OS Lite (64-bit) to your SD card',
              'Copy magora-setup.sh to the SD card root',
              'Boot your Pi — setup runs automatically',
              'Your node will appear on the map within 5 minutes',
            ].map((s, i) => (
              <div key={i} style={{ display: 'flex', gap: '10px', marginBottom: '8px', fontSize: '13px', color: C.textSub }}>
                <span style={{ color: C.accentLight, fontWeight: '700', flexShrink: 0 }}>{i + 1}.</span>
                <span>{s}</span>
              </div>
            ))}
          </div>
          <button style={btn} onClick={downloadScript}>
            Download magora-setup.sh
          </button>
        </div>
      )}

    </div>
  )
}
