import { useState } from 'react'
import { supabase } from '../lib/supabase'

const HARDWARE_OPTIONS = [
  { id: 'rpi-zero-2w', name: 'Raspberry Pi Zero 2W', sub: 'Recommended · ~$15' },
  { id: 'rpi-4', name: 'Raspberry Pi 4', sub: 'More power · ~$55' },
  { id: 'rpi-3b', name: 'Raspberry Pi 3B+', sub: 'Good balance · ~$35' },
  { id: 'other', name: 'Other / custom', sub: 'Linux SBC' },
]

const HABITAT_OPTIONS = [
  'montane-scrub', 'forest', 'grassland', 'wetland',
  'desert', 'urban-garden', 'farmland', 'coastal', 'other'
]

export default function RegisterNode() {
  const [step, setStep] = useState(1)
  const [hardware, setHardware] = useState('rpi-zero-2w')
  const [form, setForm] = useState({
    nodeName: '',
    wifi_ssid: '',
    wifi_password: '',
    lat: '',
    lon: '',
    elevation: '',
    habitat: 'montane-scrub',
  })
  const [nodeId, setNodeId] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  function update(field, value) {
    setForm(f => ({ ...f, [field]: value }))
  }

  async function registerNode() {
    setLoading(true)
    setError(null)
    try {
      const { data, error: err } = await supabase
        .from('nodes')
        .insert({
          name: form.nodeName,
          hardware_type: hardware,
          location: `POINT(${form.lon} ${form.lat})`,
          elevation_m: parseFloat(form.elevation) || null,
          habitat_type: form.habitat,
          is_active: false,
        })
        .select()
        .single()

      if (err) throw err
      setNodeId(data.id)
      setStep(4)
    } catch (e) {
      setError(e.message)
    }
    setLoading(false)
  }

  function generateScript() {
    return `#!/bin/bash
# Magora Network — Node Setup Script
# Node: ${form.nodeName}
# Generated by the Magora Portal

set -e
echo "Setting up Magora node: ${form.nodeName}"

# Configure WiFi
cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
    ssid="${form.wifi_ssid}"
    psk="${form.wifi_password}"
}
EOF

# Write location config
cat > /home/magora/location.json << EOF
{
  "lat": ${form.lat},
  "lon": ${form.lon},
  "name": "${form.nodeName}"
}
EOF

# Write secrets
cat > /home/magora/secrets.env << EOF
SUPABASE_KEY=sb_secret_nYtrj-YkZ71MJwFZQNONoA_FyntWjYl
NODE_ID=${nodeId}
EOF

chmod 600 /home/magora/secrets.env

# Install dependencies
pip install birdnetlib astral numpy requests --break-system-packages

# Enable service
sudo systemctl enable birdnet.service
sudo systemctl start birdnet.service

echo "Setup complete. Node ${form.nodeName} is now active."
`
  }

  function downloadScript() {
    const blob = new Blob([generateScript()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'magora-setup.sh'
    a.click()
  }

  const card = { background: '#fff', border: '0.5px solid #d3d1c7', borderRadius: '12px', padding: '20px' }
  const label = { display: 'block', fontSize: '12px', color: '#5f5e5a', marginBottom: '4px', fontWeight: '500' }
  const field = { marginBottom: '12px' }
  const btn = {
    width: '100%', background: '#3b6d11', color: '#c0dd97',
    border: 'none', padding: '10px', borderRadius: '8px',
    fontSize: '13px', fontWeight: '500', cursor: 'pointer', marginTop: '4px'
  }

  const steps = ['Account', 'Hardware', 'Location', 'Download']

  return (
    <div style={{ maxWidth: '480px', margin: '0 auto' }}>

      <div style={{ display: 'flex', gap: '0', marginBottom: '24px' }}>
        {steps.map((s, i) => (
          <div key={s} style={{ flex: 1, textAlign: 'center' }}>
            <div style={{
              width: '28px', height: '28px', borderRadius: '50%', margin: '0 auto 4px',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: '12px', fontWeight: '500',
              background: step > i + 1 ? '#3b6d11' : step === i + 1 ? '#fff' : '#f1efe8',
              border: step === i + 1 ? '1.5px solid #3b6d11' : step > i + 1 ? 'none' : '1.5px solid #d3d1c7',
              color: step > i + 1 ? '#f7f5f0' : step === i + 1 ? '#3b6d11' : '#888780'
            }}>
              {step > i + 1 ? '✓' : i + 1}
            </div>
            <div style={{
              fontSize: '10px',
              color: step === i + 1 ? '#3b6d11' : '#888780',
              fontWeight: step === i + 1 ? '500' : '400'
            }}>{s}</div>
          </div>
        ))}
      </div>

      {step === 1 && (
        <div style={card}>
          <div style={{ fontSize: '15px', fontWeight: '500', marginBottom: '4px' }}>Create your account</div>
          <div style={{ fontSize: '12px', color: '#888780', marginBottom: '16px' }}>Sign in to register your node</div>
          <div style={field}><label style={label}>Email</label><input type="email" placeholder="you@example.com" /></div>
          <div style={field}><label style={label}>Password</label><input type="password" placeholder="••••••••" /></div>
          <button style={btn} onClick={() => setStep(2)}>Continue</button>
        </div>
      )}

      {step === 2 && (
        <div style={card}>
          <div style={{ fontSize: '15px', fontWeight: '500', marginBottom: '4px' }}>Choose your hardware</div>
          <div style={{ fontSize: '12px', color: '#888780', marginBottom: '16px' }}>Select your compute board</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', marginBottom: '12px' }}>
            {HARDWARE_OPTIONS.map(hw => (
              <div key={hw.id} onClick={() => setHardware(hw.id)} style={{
                border: `1.5px solid ${hardware === hw.id ? '#3b6d11' : '#d3d1c7'}`,
                background: hardware === hw.id ? '#eaf3de' : '#fff',
                borderRadius: '8px', padding: '10px', cursor: 'pointer', textAlign: 'center'
              }}>
                <div style={{ fontSize: '20px', marginBottom: '4px' }}>🖥️</div>
                <div style={{ fontSize: '12px', fontWeight: '500', color: '#2c2c2a' }}>{hw.name}</div>
                <div style={{ fontSize: '10px', color: '#888780' }}>{hw.sub}</div>
              </div>
            ))}
          </div>
          <div style={field}><label style={label}>Node name</label>
            <input placeholder="e.g. birdnode2" value={form.nodeName} onChange={e => update('nodeName', e.target.value)} />
          </div>
          <button style={btn} onClick={() => setStep(3)}>Continue to location</button>
        </div>
      )}

      {step === 3 && (
        <div style={card}>
          <div style={{ fontSize: '15px', fontWeight: '500', marginBottom: '4px' }}>Location & network</div>
          <div style={{ fontSize: '12px', color: '#888780', marginBottom: '16px' }}>Where is your node and how will it connect?</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
            <div style={field}><label style={label}>Latitude</label>
              <input placeholder="38.83" value={form.lat} onChange={e => update('lat', e.target.value)} />
            </div>
            <div style={field}><label style={label}>Longitude</label>
              <input placeholder="-104.82" value={form.lon} onChange={e => update('lon', e.target.value)} />
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
            <div style={field}><label style={label}>Elevation (m)</label>
              <input placeholder="2400" value={form.elevation} onChange={e => update('elevation', e.target.value)} />
            </div>
            <div style={field}><label style={label}>Habitat type</label>
              <select value={form.habitat} onChange={e => update('habitat', e.target.value)}>
                {HABITAT_OPTIONS.map(h => <option key={h} value={h}>{h}</option>)}
              </select>
            </div>
          </div>
          <div style={field}><label style={label}>WiFi network name (SSID)</label>
            <input placeholder="MyHomeNetwork" value={form.wifi_ssid} onChange={e => update('wifi_ssid', e.target.value)} />
          </div>
          <div style={field}><label style={label}>WiFi password</label>
            <input type="password" placeholder="••••••••" value={form.wifi_password} onChange={e => update('wifi_password', e.target.value)} />
          </div>
          {error && <div style={{ color: '#a32d2d', fontSize: '12px', marginBottom: '8px' }}>{error}</div>}
          <button style={btn} onClick={registerNode} disabled={loading}>
            {loading ? 'Registering node...' : 'Register node & generate setup file'}
          </button>
        </div>
      )}

      {step === 4 && (
        <div style={card}>
          <div style={{ fontSize: '20px', marginBottom: '8px', textAlign: 'center' }}>🎉</div>
          <div style={{ fontSize: '15px', fontWeight: '500', marginBottom: '4px', textAlign: 'center' }}>
            {form.nodeName} registered!
          </div>
          <div style={{ fontSize: '12px', color: '#888780', marginBottom: '16px', textAlign: 'center' }}>
            Node ID: {nodeId}
          </div>
          <div style={{ background: '#f1efe8', borderRadius: '8px', padding: '14px', marginBottom: '16px' }}>
            <div style={{ fontSize: '12px', fontWeight: '500', marginBottom: '8px' }}>Next steps:</div>
            {[
              'Download the setup script below',
              'Flash Raspberry Pi OS Lite (64-bit) to your SD card',
              'Copy magora-setup.sh to the SD card root',
              'Boot your Pi — setup runs automatically',
              'Your node will appear on the map within 5 minutes',
            ].map((s, i) => (
              <div key={i} style={{ display: 'flex', gap: '8px', marginBottom: '6px', fontSize: '12px', color: '#2c2c2a' }}>
                <span style={{ color: '#3b6d11', fontWeight: '500', flexShrink: 0 }}>{i + 1}.</span>
                <span>{s}</span>
              </div>
            ))}
          </div>
          <button style={btn} onClick={downloadScript}>
            Download magora-setup.sh
          </button>
        </div>
      )}

    </div>
  )
}